import * as fs from 'fs'
import * as path from 'path'
import chalk from 'chalk'
import { extractProjectDictionaryKeys } from '../parser'

interface TypegenOptions {
  cwd?: string
  output?: string
}

const PLURAL_SUFFIXES = ['_zero', '_one', '_two', '_few', '_many', '_other']

export async function typegen(options: TypegenOptions = {}): Promise<void> {
  const { cwd, output = 'src/i18n.d.ts' } = options

  console.log(chalk.blue('\nGenerating TypeScript types...\n'))

  const dictEntries = await extractProjectDictionaryKeys({ cwd })

  // Collect all unique full keys (namespace:key or key)
  const allKeys = new Set<string>()

  for (const entry of dictEntries) {
    for (const key of entry.keys) {
      const fullKey = entry.namespace === 'default' ? key : `${entry.namespace}:${key}`
      allKeys.add(fullKey)

      // Also add plural base keys (strip _one, _other, etc.)
      for (const suffix of PLURAL_SUFFIXES) {
        if (key.endsWith(suffix)) {
          const baseKey = key.slice(0, -suffix.length)
          const fullBaseKey = entry.namespace === 'default' ? baseKey : `${entry.namespace}:${baseKey}`
          allKeys.add(fullBaseKey)
        }
      }
    }
  }

  if (allKeys.size === 0) {
    console.log(chalk.yellow('No dictionary keys found. Make sure loadDictionaries() calls are present.'))
    return
  }

  const sortedKeys = [...allKeys].sort()

  // Generate the .d.ts content
  const keyUnion = sortedKeys.map(k => `    | '${k}'`).join('\n')

  const content = `// Auto-generated by inline-i18n typegen
// Do not edit manually. Re-run: npx inline-i18n typegen

import 'inline-i18n-multi'

declare module 'inline-i18n-multi' {
  export type TranslationKey =
${keyUnion}

  export function t(
    key: TranslationKey,
    vars?: TranslationVars,
    locale?: string
  ): string

  export function hasTranslation(
    key: TranslationKey,
    locale?: string
  ): boolean
}
`

  const outputPath = path.resolve(cwd || process.cwd(), output)
  const outputDir = path.dirname(outputPath)

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  fs.writeFileSync(outputPath, content, 'utf-8')

  console.log(chalk.green(`Generated ${sortedKeys.length} translation key types`))
  console.log(chalk.gray(`Output: ${outputPath}\n`))

  // Show sample
  const sample = sortedKeys.slice(0, 5)
  for (const key of sample) {
    console.log(`  ${chalk.cyan(key)}`)
  }
  if (sortedKeys.length > 5) {
    console.log(chalk.gray(`  ... and ${sortedKeys.length - 5} more`))
  }
}
